//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\ycchen10\OneDrive - kochind.com\Desktop\MolexPlugIn-1899\UI\AddWorkpiece.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: ycchen10
//              Version: NX 1919
//              Date: 08-27-2020  (Format: mm-dd-yyyy)
//              Time: 15:18 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C# source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NXOpen;
using NXOpen.BlockStyler;
using NXOpen.Utilities;
using MolexPlugin.DAL;
using NXOpen.UF;
using Basic;
using MolexPlugin.Model;
using System.IO;

namespace MolexPlugin
{
    //------------------------------------------------------------------------------
    //Represents Block Styler application class
    //------------------------------------------------------------------------------
    public class AddWorkpiece
    {
        //class members
        private static Session theSession = null;
        private static UI theUI = null;
        private string theDlxFileName;
        private NXOpen.BlockStyler.BlockDialog theDialog;
        private NXOpen.BlockStyler.Group group0;// Block type: Group
        private NXOpen.BlockStyler.Group group;// Block type: Group
        private NXOpen.BlockStyler.SelectObject seleEdm;// Block type: Selection
        private NXOpen.BlockStyler.Group group1;// Block type: Group
        private NXOpen.BlockStyler.Button buttFile;// Block type: Button
        private List<string> partPaths = new List<string>();
        private UserSingleton user = UserSingleton.Instance();
        //------------------------------------------------------------------------------
        //Constructor for NX Styler class
        //------------------------------------------------------------------------------
        public AddWorkpiece()
        {
            try
            {
                theSession = Session.GetSession();
                theUI = UI.GetUI();
                theDlxFileName = "AddWorkpiece.dlx";
                theDialog = theUI.CreateDialog(theDlxFileName);
                theDialog.AddApplyHandler(new NXOpen.BlockStyler.BlockDialog.Apply(apply_cb));
                theDialog.AddOkHandler(new NXOpen.BlockStyler.BlockDialog.Ok(ok_cb));
                theDialog.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
                theDialog.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
                theDialog.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
                theDialog.AddFilterHandler(new NXOpen.BlockStyler.BlockDialog.Filter(filter_cb));
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                throw ex;
            }
        }

        //------------------------------------------------------------------------------
        //This method shows the dialog on the screen
        //------------------------------------------------------------------------------
        public NXOpen.UIStyler.DialogResponse Show()
        {
            try
            {
                if (user.UserSucceed && user.Jurisd.GetElectrodeJurisd())
                {
                    theDialog.Show();
                }

            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return 0;
        }

        //------------------------------------------------------------------------------
        //Method Name: Dispose
        //------------------------------------------------------------------------------
        public void Dispose()
        {
            if (theDialog != null)
            {
                theDialog.Dispose();
                theDialog = null;
            }
        }

        //------------------------------------------------------------------------------
        //---------------------Block UI Styler Callback Functions--------------------------
        //------------------------------------------------------------------------------

        //------------------------------------------------------------------------------
        //Callback Name: initialize_cb
        //------------------------------------------------------------------------------
        public void initialize_cb()
        {
            try
            {
                group0 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group0");
                group = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group");
                seleEdm = (NXOpen.BlockStyler.SelectObject)theDialog.TopBlock.FindBlock("seleEdm");
                group1 = (NXOpen.BlockStyler.Group)theDialog.TopBlock.FindBlock("group1");
                buttFile = (NXOpen.BlockStyler.Button)theDialog.TopBlock.FindBlock("buttFile");
                Selection.MaskTriple maskComp = new Selection.MaskTriple()
                {
                    Type = 63,
                    Subtype = 1,
                    SolidBodySubtype = 0
                };
                Selection.MaskTriple[] masks = { maskComp };
                seleEdm.SetSelectionFilter(Selection.SelectionAction.ClearAndEnableSpecific, masks);//过滤只选择组件

            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //Callback Name: dialogShown_cb
        //This callback is executed just before the dialog launch. Thus any value set 
        //here will take precedence and dialog will be launched showing that value. 
        //------------------------------------------------------------------------------
        public void dialogShown_cb()
        {
            try
            {
                //---- Enter your callback code here -----
                this.buttFile.Enable = false;
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
        }

        //------------------------------------------------------------------------------
        //Callback Name: apply_cb
        //------------------------------------------------------------------------------
        public int apply_cb()
        {
            int errorCode = 0;
            try
            {
                //---- Enter your callback code here -----
                if (this.seleEdm.GetSelectedObjects().Length > 0)
                {
                    Part workPart = theSession.Parts.Work;
                    NXOpen.Assemblies.Component ct = this.seleEdm.GetSelectedObjects()[0] as NXOpen.Assemblies.Component;
                    Part edmPart = ct.Prototype as Part;
                    List<string> err = new List<string>();
                    if (partPaths.Count > 0)
                    {
                        List<WorkpieceModel> workpiece = CreateBulder(edmPart, partPaths, out err);
                        if (workpiece.Count != 0)
                        {
                            err.AddRange(this.Load(workpiece, edmPart));
                        }
                    }
                    if (err.Count != 0)
                        ClassItem.Print(err.ToArray());
                    PartUtils.SetPartDisplay(workPart);
                    bool anyPartsModified1;
                    NXOpen.PartSaveStatus partSaveStatus1;
                    Session.GetSession().Parts.SaveAll(out anyPartsModified1, out partSaveStatus1);
                }
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                errorCode = 1;
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return errorCode;
        }

        //------------------------------------------------------------------------------
        //Callback Name: update_cb
        //------------------------------------------------------------------------------
        public int update_cb(NXOpen.BlockStyler.UIBlock block)
        {
            try
            {
                if (block == seleEdm)
                {
                    //---------Enter your code here-----------
                    if (seleEdm.GetSelectedObjects().Length > 0)
                        this.buttFile.Enable = true;
                }
                else if (block == buttFile)
                {
                    //---------Enter your code here-----------
                    partPaths = OpenFileUtils.OpenFiles("添加工件", "部件文件(*.prt*)|");

                }
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return 0;
        }

        //------------------------------------------------------------------------------
        //Callback Name: ok_cb
        //------------------------------------------------------------------------------
        public int ok_cb()
        {
            int errorCode = 0;
            try
            {
                errorCode = apply_cb();
                //---- Enter your callback code here -----
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                errorCode = 1;
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return errorCode;
        }
        //------------------------------------------------------------------------------
        //Callback Name: filter_cb
        //------------------------------------------------------------------------------
        public int filter_cb(NXOpen.BlockStyler.UIBlock block, NXOpen.TaggedObject selectedObject)
        {
            if (selectedObject is NXOpen.Assemblies.Component)
            {
                NXOpen.Assemblies.Component ct = selectedObject as NXOpen.Assemblies.Component;
                if (EDMModel.IsEDM(ct.Prototype as Part))
                    return (NXOpen.UF.UFConstants.UF_UI_SEL_ACCEPT);
            }
            return (NXOpen.UF.UFConstants.UF_UI_SEL_REJECT);
        }
        //------------------------------------------------------------------------------
        //Function Name: GetBlockProperties
        //Returns the propertylist of the specified BlockID
        //------------------------------------------------------------------------------
        public PropertyList GetBlockProperties(string blockID)
        {
            PropertyList plist = null;
            try
            {
                plist = theDialog.GetBlockProperties(blockID);
            }
            catch (Exception ex)
            {
                //---- Enter your exception handling code here -----
                theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
            }
            return plist;
        }

        private List<WorkpieceModel> CreateBulder(Part edmPart, List<string> openFiles, out List<string> err)
        {
            List<WorkpieceModel> workpiece = new List<WorkpieceModel>();
            err = new List<string>();
            EDMModel edm = new EDMModel(edmPart);
            MoldInfo moldInfo = edm.Info.MoldInfo;
            WorkPieceInfo info = new WorkPieceInfo(edm.Info.MoldInfo, user.CreatorUser);
            foreach (string st in openFiles)
            {
                MoldInfo temp = moldInfo.Clone() as MoldInfo;
                string name = Path.GetFileNameWithoutExtension(st);
                temp.WorkpieceNumber = name;
                WorkpieceModel model = new WorkpieceModel(new WorkPieceInfo(temp, user.CreatorUser));
                if (model.CreatePart(edm.WorkpieceDirectoryPath, st))
                {
                    workpiece.Add(model);
                }
                else
                {
                    err.Add(name + "没创建成功");
                }
            }
            return workpiece;
        }

        private List<string> Load(List<WorkpieceModel> workpiece, Part edmPart)
        {
            List<string> err = new List<string>();
            foreach (WorkpieceModel wm in workpiece)
            {
                try
                {
                    wm.Load(edmPart);
                }
                catch (NXException ex)
                {
                    ClassItem.WriteLogFile(wm.AssembleName + "错误      " + ex.Message);
                }

            }
            return err;
        }

    }
}
